// This file is part of the course TPV2@UCM - Samir Genaim

#pragma once

#define _CMPS_LIST_ \
	TRANSFORM, \
	IMAGE, \
	IMAGEWITHFRAMES, \
	DEACCELERATION, \
	FOLLOWMOUSE, \
	GUN, \
	DISABLEONCOLLISION, \
	GAMESTATE, \
	GENERATIONS, \
	HEALTH, \
	FIGHTERCONTROL, \
	WRAPAROUND, \
	TELEPORTONEXIT, \
	FOLLOW, \
	TOWARDDESTINATION, \
	MATERIALCONSISTENCY

#define _GRPS_LIST_ \
	ASTEROIDS, \
	FIGHTER, \
	BULLETS

#define _HDLRS_LIST_ \
	FIGHTER_HDLR, \
	ASTEROIDS_HDLR